config/routes.rb
Theraffler::Application.routes.draw do
  resources :meetup_events

end

app/models/meetup_event.rb
class MeetupEvent < ActiveRecord::Base
  attr_accessible :identifier

  def to_url
    "http://www.sfruby.info/events/#{self.identifier}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/meetup_events_controller.rb
require 'rsvp_getter'

class MeetupEventsController < ApplicationController
  # GET /meetup_events
  # GET /meetup_events.json
  def index
    @meetup_events = MeetupEvent.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @meetup_events }
    end
  end

  # GET /meetup_events/1
  # GET /meetup_events/1.json
  def show
    @meetup_event = MeetupEvent.find(params[:id])

    if api_key = ENV["MEETUP_API_KEY"]
      getter = RsvpGetter.new api_key
      response = getter.get @meetup_event.identifier
      @rsvps = response.results.shuffle
      @event_name = @rsvps.first["event"]["name"]
    else
      @rsvps = []
      flash[:notice] = "ERROR: missing API key"
    end

    event_with_rsvps = @meetup_event.attributes.merge("rsvps" => @rsvps)

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: event_with_rsvps }
      format.xml { render xml: event_with_rsvps }
    end
  end

  # GET /meetup_events/new
  # GET /meetup_events/new.json
  def new
    @meetup_event = MeetupEvent.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @meetup_event }
    end
  end

  # GET /meetup_events/1/edit
  def edit
    @meetup_event = MeetupEvent.find(params[:id])
  end

  # POST /meetup_events
  # POST /meetup_events.json
  def create
    @meetup_event = MeetupEvent.new(params[:meetup_event])

    respond_to do |format|
      if @meetup_event.save
        format.html { redirect_to @meetup_event, notice: 'Meetup event was successfully created.' }
        format.json { render json: @meetup_event, status: :created, location: @meetup_event }
      else
        format.html { render action: "new" }
        format.json { render json: @meetup_event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetup_events/1
  # PUT /meetup_events/1.json
  def update
    @meetup_event = MeetupEvent.find(params[:id])

    respond_to do |format|
      if @meetup_event.update_attributes(params[:meetup_event])
        format.html { redirect_to @meetup_event, notice: 'Meetup event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meetup_event.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meetup_events_helper.rb
module MeetupEventsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Theraffler</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/meetup_events/_form.html.erb
<%= form_for(@meetup_event) do |f| %>
  <% if @meetup_event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meetup_event.errors.count, "error") %> prohibited this meetup_event from being saved:</h2>

      <ul>
      <% @meetup_event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :identifier %><br />
    <%= f.text_field :identifier %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetup_events/edit.html.erb
<h1>Editing meetup_event</h1>

<%= render 'form' %>

<%= link_to 'Show', @meetup_event %> |
<%= link_to 'Back', meetup_events_path %>

app/views/meetup_events/index.html.erb
<h1>Listing meetup_events</h1>

<table>
  <tr>
    <th>Identifier</th>
    <th>URL</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%
   @meetup_events.each do |meetup_event|
     url = meetup_event.to_url
   %>
  <tr>
    <td><%= meetup_event.identifier %></td>
    <td><%= link_to url, url %></td>
    <td><%= link_to 'Raffle', meetup_event %></td>
    <td><%= link_to 'Edit', edit_meetup_event_path(meetup_event) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meetup event', new_meetup_event_path %>

app/views/meetup_events/new.html.erb
<h1>New meetup_event</h1>

<%= render 'form' %>

<%= link_to 'Back', meetup_events_path %>

app/views/meetup_events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Event Name:</b>
  <%= @event_name %>
</p>

<p>
  <b>Identifier:</b>
  <%= @meetup_event.identifier %>
</p>

<p>
  <b>URL:</b>
  <%=
     url = @meetup_event.to_url
     link_to url, url
     %>
</p>

<p>
  <table>
    <tr>
      <th></th>
      <th>Name</th>
      <th>Profile</th>
    </tr>
    <% @rsvps.each do |rsvp| %>
    <tr>
      <td><%=
             foto = rsvp["member_photo"]
             image_tag(
               foto ? rsvp["member_photo"]["thumb_link"] : "/images/spacer.gif",
               :height => 80)
        %>
      </td>
      <td><%= rsvp["member"]["name"] %></td>
      <td><%=
             member_ident = rsvp["member"]["member_id"]
             url = "http://www.sfruby.info/members/#{member_ident}/"
             link_to url, url
             %>
      </td>
    </tr>
    <% end %>
  </table>
</p>

<%= link_to 'Edit', edit_meetup_event_path(@meetup_event) %> |
<%= link_to 'Back', meetup_events_path %>